# Generated by Django 3.2 on 2021-04-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210417_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(max_length=255, unique=True, verbose_name='Данные паспорта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zagranpassport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные загранпаспорта'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='pas_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость загранпаспорта'),
        ),
        migrations.AlterField(
            model_name='country',
            name='visa_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость визы'),
        ),
        migrations.AlterField(
            model_name='meansoftransport',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='begin_date',
            field=models.DateTimeField(verbose_name='Дата и время отправления'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата и время возвращения'),
        ),
        migrations.AlterField(
            model_name='sellpermit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='sellpermit',
            name='price_disc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
